version: '3'
services:
  app:
    container_name: main_app
    build: .
    ports:
      - "10000:8080"
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${dbname}
      - DATABASE_HOST=${host}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
